n = int(input('Digite um número para ver sua taboada '))
print(n, '+  1 = {}'.format(n+1))
print(n, '+  2 = {}'.format(n+2))
print(n, '+  3 = {}'.format(n+3))
print(n, '+  4 = {}'.format(n+4))
print(n, '+  5 = {}'.format(n+5))
print(n, '+  6 = {}'.format(n+6))
print(n, '+  7 = {}'.format(n+7))
print(n, '+  8 = {}'.format(n+8))
print(n, '+  9 = {}'.format(n+9))
print(n, '+ 10 = {}'.format(n+10))
print('=0=' *4)
print('{} - {:2} = {}'.format(n+1, n, n+1-n))
print('{} - {:2} = {}'.format(n+2, n, n+2-n))
print('{} - {:2} = {}'.format(n+3, n, n+3-n))
print('{} - {:2} = {}'.format(n+4, n, n+4-n))
print('{} - {:2} = {}'.format(n+5, n, n+5-n))
print('{} - {:2} = {}'.format(n+6, n, n+6-n))
print('{} - {:2} = {}'.format(n+7, n, n+7-n))
print('{} - {:2} = {}'.format(n+8, n, n+8-n))
print('{} - {:2} = {}'.format(n+9, n, n+9-n))
print('{} - {:2} = {}'.format(n+10, n, n+10-n))
print('=^=' *4)
print(n, 'X  1 = {}'.format(n*1))
print(n, 'X  2 = {}'.format(n*2))
print(n, 'X  3 = {}'.format(n*3))
print(n, 'X  4 = {}'.format(n*4))
print(n, 'X  5 = {}'.format(n*5))
print(n, 'X  6 = {}'.format(n*6))
print(n, 'X  7 = {}'.format(n*7))
print(n, 'X  8 = {}'.format(n*8))
print(n, 'X  9 = {}'.format(n*9))
print(n, 'X 10 = {}'.format(n*10))
print('=^=' *4)
print('{:2} / {:2} = {}'.format(n*1, n, n*1/n))
print('{} / {:2} = {}'.format(n*2, n, n*2/n))
print('{} / {:2} = {}'.format(n*3, n, n*3/n))
print('{} / {:2} = {}'.format(n*4, n, n*4/n))
print('{} / {:2} = {}'.format(n*5, n, n*5/n))
print('{} / {:2} = {}'.format(n*6, n, n*6/n))
print('{} / {:2} = {}'.format(n*7, n, n*7/n))
print('{} / {:2} = {}'.format(n*8, n, n*8/n))
print('{} / {:2} = {}'.format(n*9, n, n*9/n))
print('{} / {:2} = {}'.format(n*10, n, n*10/n))
print('=^=' *4)